### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang-stubs#1]
Is it really called `polylang-pro-stubs`?

https://github.com/polylang/polylang-stubs/blob/38a09793b4d822ea1e5914384094ff301c35174a/finder.php#L6

**Comment by Chouby** [comment]
It indeed includes all the stubs for Polylang and Polylang Pro. I named it `polylang-stubs` anyway as it looked more generic to me. I hope the readme that I just pushed make things clearer.

**Comment by szepeviktor** [comment]
Thank you.
